<package format="2">
  <name>marine_tools</name>
  <version>0.1.0</version>
  <description>
    Marine data tools
  </description>

  <maintainer email="roland@ccom.unh.edu">Roland Arsenault</maintainer>
  <author>Roland Arsenault</author>

  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>marine_acoustic_msgs</depend>
  <depend>pcl_ros</depend>
  <depend>rclcpp</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
